In [35]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [36]:
# Load dataset 
df = pd.read_csv("Churn_Modelling.csv")
print(df.head())

   RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         790

In [37]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [38]:
print("Number of row:",df.shape[0])
print("Number of columns:",df.shape[1])

Number of row: 10000
Number of columns: 14


In [39]:
# Preprocing 
# Droping the irrelevent c(olumns)features 
df=df.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [40]:
# Encoding the Categorical varibles 
label_encoder_gender=LabelEncoder()
df['Gender']=label_encoder_gender.fit_transform(df['Gender'])
df

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France       0   42       2       0.00              1   
1             608     Spain       0   41       1   83807.86              1   
2             502    France       0   42       8  159660.80              3   
3             699    France       0   39       1       0.00              2   
4             850     Spain       0   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France       1   39       5       0.00              2   
9996          516    France       1   35      10   57369.61              1   
9997          709    France       0   36       7       0.00              1   
9998          772   Germany       1   42       3   75075.31              2   
9999          792    France       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [41]:

from sklearn.preprocessing import OneHotEncoder
one_hot_geo=OneHotEncoder()
geo_encoder= one_hot_geo.fit_transform(df[['Geography']])

In [42]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [43]:
new=one_hot_geo.get_feature_names_out(['Geography'])

In [44]:
geo_encoder_df=pd.DataFrame(geo_encoder.toarray(),columns=new)

In [45]:
# combined one hot encoded columns with original data

df=pd.concat([df.drop('Geography',axis=1),geo_encoder_df],axis=1)

df.head()


CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1               1.0   
1               1        112542.58       0               0.0   
2               0        113931.57       1               1.0   
3               0         93826.63       0               1.0   
4               1         79084.10       0               0.0   

   Geography_Germany  Geography_Spain  
0                0.0              0.0  
1                0.0              1.0  
2                0.0              0.0  
3                0.0              0.0  
4                0.0              1.0

In [46]:
# save the Encoder and scaler 
with open('label_encoder_gender.pkl','wb')as file:
    pickle.dump(label_encoder_gender,file)


with open('one_hot_geo.pkl','wb')as file:
    pickle.dump(one_hot_geo,file)

In [47]:
## Divide the Data Set into independent and dependent feature 
# Exited as dependent and other are the independent features

X = df.drop('Exited',axis=1)
y = df['Exited']

In [48]:
#Spliting the data set into training and testing 
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [49]:
# Scale these features 
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [50]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [51]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [52]:
# save scaler file in pickle 
with open('scaler.pkl','wb')as file:
    pickle.dump(scaler,file)

## ANN Implementation 

In [53]:
import tensorflow as tf 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [54]:
(X_train.shape[1],)

(12,)

In [55]:
#Build the ANN model 
model = Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), # HL1 connected with i/p layer
    Dense(32,activation='relu'), # HL 2 layer
    Dense(1,activation='sigmoid') # out put layer 
])

In [56]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 64)                832       
                                                                 
 dense_4 (Dense)             (None, 32)                2080      
                                                                 
 dense_5 (Dense)             (None, 1)                 33        
                                                                 
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [57]:
# Define the optimizer and loss function
import tensorflow 
opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)
losses = tensorflow.keras.losses.BinaryCrossentropy()

In [58]:
## In order forword and backword propogation need to compile model
# Assuming 'model' is your neural network model
model.compile(optimizer=opt, loss=losses, metrics=['accuracy'])

In [59]:
# Set up the Tensorboard 

log_dir='log/fit' + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)


In [60]:
# Early stopping callback to prevent overfitting (based on validation loss)
from tensorflow.keras.callbacks import EarlyStopping

# Define the EarlyStopping callback
early_stopping_callback = EarlyStopping(
    monitor='val_loss',   # Monitor validation loss
    patience=15,           # Number of epochs with no improvement before stopping
    restore_best_weights=True  # Restore the model weights from the best epoch
)


In [61]:
# Train model 
histroy = model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3982 - accuracy: 0.8370 - val_loss: 0.3441 - val_accuracy: 0.8610
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3562 - accuracy: 0.8522 - val_loss: 0.3593 - val_accuracy: 0.8590
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3476 - accuracy: 0.8570 - val_loss: 0.3477 - val_accuracy: 0.8575
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3423 - accuracy: 0.8595 - val_loss: 0.3437 - val_accuracy: 0.8535
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3418 - accuracy: 0.8609 - val_loss: 0.3529 - val_accuracy: 0.8560
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3399 - accuracy: 0.8608 - val_loss: 0.3469 - val_accuracy: 0.8615
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3367 - accuracy: 0.8611 - val_loss: 0.3437 - val_accuracy: 0.8600

In [62]:
model.save('model.h5')

c:\Churn Prediction ANN\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
